import { defineSchema } from "convex/server";

import {
  aiDomainValidator,
  aiMemoryConfidenceValidator,
  aiMemoryTable,
  approvalModeValidator,
  approvalRequestsTable,
  approvalRequestStatusValidator,
} from "./schema/ai";
import {
  domainStatusValidator,
  userDomainsTable,
} from "./schema/domains";
import {
  activityAssignmentsTable,
  activityAssignedByValidator,
  activityAssignmentStatusValidator,
  activityCategoryValidator,
  activityDifficultyValidator,
  activityEventsTable,
  activityReflectionsTable,
  activitySignalMapEntryValidator,
  activitySourceValidator,
  activityTemplatesTable,
  confidenceScoresTable,
  feedbackTable,
  onboardingBiggestBlockerValidator,
  onboardingCommitmentLevelValidator,
  onboardingEnergyPatternValidator,
  onboardingPhaseValidator,
  onboardingPreferredStyleValidator,
  onboardingPrimaryGoalValidator,
  onboardingStageValidator,
  onboardingStateTable,
  signalActionValidator,
  signalsTable,
  suggestionVerdictValidator,
  suggestionsTable,
  userProfileNotificationsValidator,
  userProfileTable,
} from "./schema/onboarding";

export {
  activityAssignedByValidator,
  activityAssignmentStatusValidator,
  activityCategoryValidator,
  activityDifficultyValidator,
  activitySignalMapEntryValidator,
  activitySourceValidator,
  aiDomainValidator,
  aiMemoryConfidenceValidator,
  approvalModeValidator,
  approvalRequestStatusValidator,
  domainStatusValidator,
  onboardingBiggestBlockerValidator,
  onboardingCommitmentLevelValidator,
  onboardingEnergyPatternValidator,
  onboardingPhaseValidator,
  onboardingPreferredStyleValidator,
  onboardingPrimaryGoalValidator,
  onboardingStageValidator,
  signalActionValidator,
  suggestionVerdictValidator,
  userProfileNotificationsValidator,
};

export default defineSchema({
  aiMemory: aiMemoryTable,
  approvalRequests: approvalRequestsTable,
  userDomains: userDomainsTable,
  userProfile: userProfileTable,
  onboardingState: onboardingStateTable,
  activityTemplates: activityTemplatesTable,
  activityAssignments: activityAssignmentsTable,
  activityEvents: activityEventsTable,
  activityReflections: activityReflectionsTable,
  signals: signalsTable,
  suggestions: suggestionsTable,
  feedback: feedbackTable,
  confidenceScores: confidenceScoresTable,
});
