import { defineSchema } from "convex/server";

import {
  aiDomainValidator,
  aiMemoryConfidenceValidator,
  aiMemoryTable,
  approvalModeValidator,
  approvalRequestsTable,
  approvalRequestStatusValidator,
} from "./schema/ai";
import {
  onboardingStageValidator,
  onboardingPhaseValidator,
  onboardingStateTable,
  onboardingBiggestBlockerValidator,
  onboardingCommitmentLevelValidator,
  onboardingEnergyPatternValidator,
  onboardingPreferredStyleValidator,
  onboardingPrimaryGoalValidator,
  userProfileTable,
  activityCategoryValidator,
  activityTemplatesTable,
  activityAssignmentsTable,
  activityEventsTable,
  activityReflectionsTable,
  activityDifficultyValidator,
  activitySourceValidator,
  activityAssignmentStatusValidator,
  activityAssignedByValidator,
  suggestionVerdictValidator,
  signalsTable,
  suggestionsTable,
  feedbackTable,
  confidenceScoresTable,
} from "./schema/onboarding";
export {
  aiDomainValidator,
  aiMemoryConfidenceValidator,
  approvalModeValidator,
  approvalRequestStatusValidator,
} from "./schema/ai";
export {
  onboardingStageValidator,
  onboardingPhaseValidator,
  onboardingBiggestBlockerValidator,
  onboardingCommitmentLevelValidator,
  onboardingEnergyPatternValidator,
  onboardingPreferredStyleValidator,
  onboardingPrimaryGoalValidator,
  activityCategoryValidator,
  activityDifficultyValidator,
  activitySourceValidator,
  activityAssignmentStatusValidator,
  activityAssignedByValidator,
  suggestionVerdictValidator,
};

export default defineSchema({
  aiMemory: aiMemoryTable,
  approvalRequests: approvalRequestsTable,
  userProfile: userProfileTable,
  onboardingState: onboardingStateTable,
  activityTemplates: activityTemplatesTable,
  activityAssignments: activityAssignmentsTable,
  activityEvents: activityEventsTable,
  activityReflections: activityReflectionsTable,
  signals: signalsTable,
  suggestions: suggestionsTable,
  feedback: feedbackTable,
  confidenceScores: confidenceScoresTable,
});
